import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/components/_Theme/ThemeProvider";

const sulphur = localFont({ src: "./src/fonts/Sulphur_Point/SulphurPoint-Regular.ttf", variable: "--font-sulphur" });
const borel   = localFont({ src: "./src/fonts/Borel/Borel-Regular.ttf", variable: "--font-borel" });
const funnel  = localFont({ src: "./src/fonts/Funnel_Sans/FunnelSans-VariableFont_wght.ttf", variable: "--font-funnel" });
const vend    = localFont({ src: "./src/fonts/Vend_Sans/VendSans-VariableFont_wght.ttf", variable: "--font-vend" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="chill">
      <body className={`${borel.variable} ${sulphur.variable} ${funnel.variable} ${vend.variable}`}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}