// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lumify.api.Models.Context;

#nullable disable

namespace lumify.api.Migrations
{
    [DbContext(typeof(LumifyDbContext))]
    [Migration("20260618062912_AddPasswordResetToken")]
    partial class AddPasswordResetToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("lumify.api.Models.EF.ChatMessage", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "RoomID" }, "ix_chatmessage_room");

                    b.HasIndex(new[] { "RoomID", "CreatedAt" }, "ix_chatmessage_room_created");

                    b.HasIndex(new[] { "SenderID" }, "ix_chatmessage_sender");

                    b.ToTable("ChatMessage", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.Event", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsAllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "OwnerID" }, "ix_event_owner");

                    b.HasIndex(new[] { "OwnerID", "StartDate" }, "ix_event_owner_start");

                    b.HasIndex(new[] { "WorkspaceID" }, "ix_event_workspace");

                    b.HasIndex(new[] { "WorkspaceID", "StartDate" }, "ix_event_workspace_start");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.Folder", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentFolderID")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "OwnerID" }, "ix_folder_owner");

                    b.HasIndex(new[] { "ParentFolderID" }, "ix_folder_parent");

                    b.HasIndex(new[] { "WorkspaceID" }, "ix_folder_workspace");

                    b.HasIndex(new[] { "OwnerID", "ParentFolderID", "Name" }, "ux_folder_private_parent_name")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerID", "Name" }, "ux_folder_private_root_name")
                        .IsUnique();

                    b.HasIndex(new[] { "WorkspaceID", "ParentFolderID", "Name" }, "ux_folder_workspace_parent_name")
                        .IsUnique();

                    b.HasIndex(new[] { "WorkspaceID", "Name" }, "ux_folder_workspace_root_name")
                        .IsUnique();

                    b.ToTable("Folder", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.Friendship", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddresseeID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserHighID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserLowID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "AddresseeID" }, "ix_friendship_addressee");

                    b.HasIndex(new[] { "RequesterID" }, "ix_friendship_requester");

                    b.HasIndex(new[] { "Status" }, "ix_friendship_status");

                    b.HasIndex(new[] { "UserHighID" }, "ix_friendship_userhigh");

                    b.HasIndex(new[] { "UserLowID" }, "ix_friendship_userlow");

                    b.HasIndex(new[] { "UserLowID", "UserHighID" }, "ux_friendship_pair")
                        .IsUnique()
                        .HasFilter("DeletedAt IS NULL");

                    b.ToTable("Friendship", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.Note", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "FolderID" }, "ix_note_folder");

                    b.HasIndex(new[] { "OwnerID" }, "ix_note_owner");

                    b.HasIndex(new[] { "WorkspaceID" }, "ix_note_workspace");

                    b.HasIndex(new[] { "OwnerID", "FolderID", "Name" }, "ux_note_private_folder_name")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerID", "Name" }, "ux_note_private_root_name")
                        .IsUnique();

                    b.HasIndex(new[] { "WorkspaceID", "FolderID", "Name" }, "ux_note_workspace_folder_name")
                        .IsUnique();

                    b.HasIndex(new[] { "WorkspaceID", "Name" }, "ux_note_workspace_root_name")
                        .IsUnique();

                    b.ToTable("Note", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.NoteAttachment", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "NoteID" }, "ix_noteattachment_note");

                    b.HasIndex(new[] { "OwnerID" }, "ix_noteattachment_owner");

                    b.ToTable("NoteAttachment", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.Note_LinkItem", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NotePos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "NoteID" }, "ix_note_linkitem_note");

                    b.ToTable("Note_LinkItem", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.Note_TextBlock", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsCollapsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NotePos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "NoteID" }, "ix_note_textblock_note");

                    b.ToTable("Note_TextBlock", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.PasswordResetToken", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "UserID" }, "ix_passwordresettoken_user");

                    b.HasIndex(new[] { "TokenHash" }, "ux_passwordresettoken_hash")
                        .IsUnique();

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.TodoEntry", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TodoListID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "TodoListID" }, "ix_todoentry_list");

                    b.HasIndex(new[] { "OwnerID" }, "ix_todoentry_owner");

                    b.ToTable("TodoEntry", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.TodoList", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "OwnerID" }, "ix_todolist_owner");

                    b.HasIndex(new[] { "WorkspaceID" }, "ix_todolist_workspace");

                    b.ToTable("TodoList", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Email" }, "ux_user_email")
                        .IsUnique()
                        .HasFilter("DeletedAt IS NULL");

                    b.HasIndex(new[] { "Username" }, "ux_user_username")
                        .IsUnique()
                        .HasFilter("DeletedAt IS NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.Workspace", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "OwnerID", "Name" }, "ux_workspace_owner_name")
                        .IsUnique();

                    b.ToTable("Workspace", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.WorkspaceMember", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkspaceID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "UserID" }, "ix_workspacemember_user");

                    b.HasIndex(new[] { "WorkspaceID" }, "ix_workspacemember_workspace");

                    b.HasIndex(new[] { "WorkspaceID", "UserID" }, "ux_workspacemember_unique")
                        .IsUnique();

                    b.ToTable("WorkspaceMember", (string)null);
                });

            modelBuilder.Entity("lumify.api.Models.EF.ChatMessage", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderID")
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Event", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "Owner")
                        .WithMany("Events")
                        .HasForeignKey("OwnerID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.Workspace", "Workspace")
                        .WithMany("Events")
                        .HasForeignKey("WorkspaceID");

                    b.Navigation("Owner");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Folder", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "Owner")
                        .WithMany("Folders")
                        .HasForeignKey("OwnerID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.Folder", "ParentFolder")
                        .WithMany("InverseParentFolder")
                        .HasForeignKey("ParentFolderID");

                    b.HasOne("lumify.api.Models.EF.Workspace", "Workspace")
                        .WithMany("Folders")
                        .HasForeignKey("WorkspaceID");

                    b.Navigation("Owner");

                    b.Navigation("ParentFolder");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Friendship", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.User", "UserHigh")
                        .WithMany("FriendshipsAsUserHigh")
                        .HasForeignKey("UserHighID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.User", "UserLow")
                        .WithMany("FriendshipsAsUserLow")
                        .HasForeignKey("UserLowID")
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");

                    b.Navigation("UserHigh");

                    b.Navigation("UserLow");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Note", b =>
                {
                    b.HasOne("lumify.api.Models.EF.Folder", "Folder")
                        .WithMany("Notes")
                        .HasForeignKey("FolderID");

                    b.HasOne("lumify.api.Models.EF.User", "Owner")
                        .WithMany("Notes")
                        .HasForeignKey("OwnerID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.Workspace", "Workspace")
                        .WithMany("Notes")
                        .HasForeignKey("WorkspaceID");

                    b.Navigation("Folder");

                    b.Navigation("Owner");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("lumify.api.Models.EF.NoteAttachment", b =>
                {
                    b.HasOne("lumify.api.Models.EF.Note", "Note")
                        .WithMany("NoteAttachments")
                        .HasForeignKey("NoteID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.User", "Owner")
                        .WithMany("NoteAttachments")
                        .HasForeignKey("OwnerID")
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Note_LinkItem", b =>
                {
                    b.HasOne("lumify.api.Models.EF.Note", "Note")
                        .WithMany("Note_LinkItems")
                        .HasForeignKey("NoteID")
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Note_TextBlock", b =>
                {
                    b.HasOne("lumify.api.Models.EF.Note", "Note")
                        .WithMany("Note_TextBlocks")
                        .HasForeignKey("NoteID")
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("lumify.api.Models.EF.PasswordResetToken", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("lumify.api.Models.EF.TodoEntry", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "Owner")
                        .WithMany("TodoEntries")
                        .HasForeignKey("OwnerID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.TodoList", "TodoList")
                        .WithMany("TodoEntries")
                        .HasForeignKey("TodoListID")
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("lumify.api.Models.EF.TodoList", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "Owner")
                        .WithMany("TodoLists")
                        .HasForeignKey("OwnerID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.Workspace", "Workspace")
                        .WithMany("TodoLists")
                        .HasForeignKey("WorkspaceID");

                    b.Navigation("Owner");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Workspace", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "Owner")
                        .WithMany("Workspaces")
                        .HasForeignKey("OwnerID")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("lumify.api.Models.EF.WorkspaceMember", b =>
                {
                    b.HasOne("lumify.api.Models.EF.User", "User")
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("UserID")
                        .IsRequired();

                    b.HasOne("lumify.api.Models.EF.Workspace", "Workspace")
                        .WithMany("WorkspaceMembers")
                        .HasForeignKey("WorkspaceID")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Folder", b =>
                {
                    b.Navigation("InverseParentFolder");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Note", b =>
                {
                    b.Navigation("NoteAttachments");

                    b.Navigation("Note_LinkItems");

                    b.Navigation("Note_TextBlocks");
                });

            modelBuilder.Entity("lumify.api.Models.EF.TodoList", b =>
                {
                    b.Navigation("TodoEntries");
                });

            modelBuilder.Entity("lumify.api.Models.EF.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Events");

                    b.Navigation("Folders");

                    b.Navigation("FriendshipsAsUserHigh");

                    b.Navigation("FriendshipsAsUserLow");

                    b.Navigation("NoteAttachments");

                    b.Navigation("Notes");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");

                    b.Navigation("TodoEntries");

                    b.Navigation("TodoLists");

                    b.Navigation("WorkspaceMembers");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("lumify.api.Models.EF.Workspace", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Folders");

                    b.Navigation("Notes");

                    b.Navigation("TodoLists");

                    b.Navigation("WorkspaceMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
